<?php

use Drupal\entity_change_tracking\Controller\EntityChangeTrackingController;

/**
 * Implements hook_entity_presave().
 */
function entity_change_tracking_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if (!$entity->isNew())
    (new EntityChangeTrackingController())->handleChangedEntity($entity);
}

/**
 * Implements hook_entity_insert().
 */
function entity_change_tracking_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  (new EntityChangeTrackingController())->handleNewEntity($entity);
}
